### ISSUE TITLE
Question: Can you preserve position using indentation?

### ISSUE THREAD

**Issue by arran4** [alexhallam/fwdt#3]
Is there a flag or something?

I am thinking something like a Ditto Mark perhaps?
https://en.wikipedia.org/wiki/Ditto_mark

**Comment by alexhallam** [comment]
Sure. Initially I was thinking of some kind of dito mark, but that would add to the character count. I sacrificed some flexibility there.

But I love the idea of adding a flag for a csv file that has a dito marks.

I would be happy to add that.

**Comment by alexhallam** [comment]
What do you think a good mark would be.

**Comment by arran4** [comment]
No idea TBH.. I mean `"` is kind of universal, but even just spacing it out would be good.

Unicode / emoticons would be very distinct. I can't imagine not making this configurable.

**Comment by alexhallam** [comment]
For sure, I just wanted to make sure that if you had some thoughts you had a chance to lay them out. 

I can add a flag for ditto that will default to `"`, but users to also specify their own mark.

Thanks again for the suggestion.

**Comment by alexhallam** [comment]
I merged #4 let me know if that is what you were thinking @arran4. I used `.` as opposed to `"` because sometimes and open quote expects a closing quote.
